apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aquasecurity.github.io/helm-charts
    chart: trivy-operator
    targetRevision: 0.20.3
    helm:
      releaseName: trivy-operator
      values: |
        operator:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
        trivy:
          ignoreUnfixed: true
          severity: HIGH,CRITICAL
          timeout: 5m
        serviceMonitor:
          enabled: true
  destination:
    name: cluster-prd
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
