apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://example.com/your/repo.git
    targetRevision: HEAD
    path: gitops-environment/addons/dev
  destination:
    name: cluster-dev
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
